# Tên của quy trình tự động hóa
name: Deploy Frontend to GitHub Pages

# Kích hoạt quy trình mỗi khi có code mới được đẩy lên nhánh "main"
on:
  push:
    branches: ["main"]
  # Cho phép chạy thủ công từ tab Actions
  workflow_dispatch:

# Cấp quyền cho quy trình để ghi vào GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Các công việc cần thực hiện
jobs:
  build-and-deploy:
    environment:
      name: production
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      # 1. Lấy mã nguồn từ kho chứa về
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Cài đặt Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # 3. Cài đặt các thư viện (trong thư mục frontend)
      - name: Install dependencies
        run: npm install
        working-directory: frontend

      # 4. SỬA LỖI: Cấp quyền thực thi cho react-scripts (trong thư mục frontend)
      - name: Add execute permission
        run: chmod +x ./node_modules/.bin/react-scripts
        working-directory: frontend

      # 5. Build dự án (trong thư mục frontend)
      - name: Build project
        run: npm run build
        working-directory: frontend
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}

      # 6. Cấu hình GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v5

      # 7. Tải lên các file đã build
      # THAY ĐỔI Ở ĐÂY: Sử dụng Actions để di chuyển output
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './frontend/build' # Đảm bảo đường dẫn này đúng là nơi build tạo ra files

       # 8. Deploy lên GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          target_branch: main # Thêm dòng này để đẩy lên nhánh main